project_name: cntb
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: contabo-gmbh
    name: cntb
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## Features
    List of newly introduced features:
    - Item 1
    - Item 2
    ## Bug fixes
    List of fixed issues:
    - Item 1
    - Item 2
    ## Code changes
    - Item 1
    - Item 2
  footer: |
    ## Thanks!
    Read more on our documentation page: https://github.com/contabo-gmbh/cntb

nfpms:
  - maintainer: contabo-gmbh
    description: "Contabo CLI for managing Contabo account"
    homepage: "https://github.com/contabo-gmbh/cntb"
    license: "GPL v3"
    formats:
      - deb
      - rpm
      - apk
    replacements:
      amd64: 64-bit
      darwin: macOS
      linux: Tux

